server:
  host: "0.0.0.0"
  port: "8080"
  idle_timeout: 120s
  read_timeout: 10s
  write_timeout: 10s

database:
  host: "db"
  port: "5432"
  user: "dev"
  password: "dev"
  db_name: "dev"
  ssl_mode: "disable"